alias -s proxy-wget2 'wget2 --http-proxy=http://localhost:8800'
alias -s proxy-go 'http_proxy=http://localhost:8800 go'
alias -s proxy-curl 'curl -x socks5h://localhost'
alias -s proxy-apt 'apt -o Acquire::http::Proxy=socks5h://localhost'
alias -s proxy-aria2c 'aria2c --all-proxy=http://localhost:8800'
alias -s gh 'all_proxy=http://localhost:8800 command gh'
alias -s gdb 'gdb -quiet'
alias -s ls 'exa --group-directories-first -aF'
